### PR TITLE
Mb/53 - Add ground transparency slider to basemap gallery widget

### LINKED ISSUE #53: Add ability to change base map transparency (Like in scene viewer)

### PR DESCRIPTION
**Pull request by MatteoBerg**
This PR resolves #53, adding the ability to adjust basemap/ground transparency which will allow users to view objects underground.

I imitated styling of the ground transparency slider in the Central Basin 3D Scene - v1.3 beta scene shown here:

image

Here is a demo showing the added functionality matching the above example scene:

[basemap-transparency.webm](https://user-images.githubusercontent.com/94854808/200663135-c36d438b-d616-407a-b633-430da1351328.webm)

### CODE REVIEW

**Comment by tbock** [comment]
It looks like you are not setting the slider to the current value of the basemap's transparency when it loads. Can you confirm/fix @MatteoBerg

**Review by tbock — CHANGES_REQUESTED** [review]
Fix slider start value

**Comment by MatteoBerg** [comment]
> Fix slider start value

Changed slider start value from 1 to map.ground.opacity value when slider is created.

**Comment by tbock** [comment]
Slider is wrong after selecting a slide then opening the base map gallery again.  The slider is still at old value not the value of the current ground opacity. @MatteoBerg

**Comment by MatteoBerg** [comment]
Feature is included in branch mb/47, PR #104

**Pull request closed without merging**
